### PR TITLE
use semantic versioning for jar-dependency runtime dependency

### PR DESCRIPTION
**Pull request by mkristian**

### CODE REVIEW

**Comment by rtyler** [comment]
@mkristian doesn't hermann require a jar-dependencies of at least a certain baseline version? I think we had some bug fixes go into 0.1.12-0.1.15 that were required for hermann to work properly

**Comment by mkristian** [comment]
not that I am aware of. 0.1.15 was the last one. probably safe to add a '>=
0.1.12' with the semantic part.

**Comment by mkristian** [comment]
now I need to squash those two commits.

**Comment by mkristian** [comment]
@rtyler squashed and now semantic version with baseline version

**Comment by rtyler** [comment]
```
Illformed requirement ["=> 0.1.10"] from
  /home/travis/build/lookout/hermann/hermann.gemspec:36:in `eval_gemspec'
```

Interesting that only one of the versions of Ruby fails with that

**Comment by mkristian** [comment]
only jruby does include the jar-dependencies dependency so only one failed :)

**Comment by rtyler** [comment]
@mkristian heh, right you are, I only quickly glanced at this yesterday and *clearly* didn't read anything

**Pull request merged**
