### PR TITLE
cleanup warnings

### PR DESCRIPTION
**Pull request by osheroff**
- fix partition selection function
- get ruby >= 2 calling the correct no-gvl function (it has HAVE_RB_THREAD_BLOCKING_REGION, it's just deprecated)

### CODE REVIEW

**Comment by rtyler** [comment]
This fails on Ruby 1.8.7, which I regret to say, I'm still trying to support. `ruby/version`h` is non-existent in Ruby 1.8.. Do you know of a macro vavailable which would otherwise indicate the compiler is running with 1.9+?

**Comment by osheroff** [comment]
shouldn't be too hard to do a condition include in extconf.rb.  will fix.

**Comment by osheroff** [comment]
ok @rtyler this fixes 1.8.7.  jruby is still apparently a flaky thing for travis, but the rest pass....

**Comment by rtyler** [comment]
@osheroff I re-triggered the JRuby build, there's something about builds in Travis that result in JBundler timing out when it attempts to contact Maven Central for Java dependencies; haven't been able to cajole that into working consistently :/

**Pull request merged**
